# Generated by Django 3.2.5 on 2021-07-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ideastartapper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideastartapper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.startapper'),
        ),
    ]
