# Generated by Django 3.2.5 on 2021-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_allusersidea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusersidea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='alluser_ideas'),
        ),
    ]
